variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode -ntp --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  GIT_STRATEGY: clone
  APP_PORTS: "8040 7040"
  GITURL_CICD: "https://user:$release_token@git.gns.cri.nz/applications/cicdutils.git"
  TEAM: "Applications"

image: maven:3-openjdk-11

stages:
  - build
  - deploy
  - image
  - deploy-prod

default:
  before_script:
    - cp $settings_xml ~/.m2/settings.xml

.deploy_template:
  tags:
    - linux
  when: manual
  before_script:
      - git clone $GITURL_CICD
      - export APP_NAME="$( ./cicdutils/pom_app_name.sh)"
  after_script:
      - rm -rf cicdutils
      - git clean -fdX 

build:
  tags:
    - docker
  stage: build
  except:
    - master
  script: |
    mvn $MAVEN_CLI_OPTS clean deploy

release:
  tags:
    - docker
  stage: deploy
  only:
    - master
  script: |
    git config user.name "\"$GITLAB_USER_NAME\""
    git config user.email "\"$GITLAB_USER_EMAIL\""
    git config http.sslverify false
    git remote set-url --push origin "https://gitlab-project-token:$release_token@git.gns.cri.nz/$CI_PROJECT_PATH.git"
    git config pull.ff only
    mvn $MAVEN_CLI_OPTS -Pprod gitflow:release-start
    mvn $MAVEN_CLI_OPTS -Pprod gitflow:release-finish

deploy-dev:
  stage: deploy
  extends: .deploy_template    
  script: |
    export VERSION="current"
    export APP_SERVER="Applications Development"
    appName="$APP_NAME"
    volSuffix="-dev"
    port=8040
    ./deploy.sh "$appName" "$port" "$volSuffix" "staging" "gns-libs-snapshot"

deploy-staging:
  stage: deploy
  extends: .deploy_template     
  script: |
    export VERSION="current"
    export APP_SERVER="GNS Web Application Staging"
    appName="$APP_NAME-dev" 
    volSuffix="-dev"
    port=8040
    ./deploy.sh "$appName" "$port" "$volSuffix" "staging" "gns-libs-snapshot"


# Set DEFAULT_SITE_API_URL=https://online-[your username].gns.cri.nz/site/api/v1 in 
# your FRED/petlab's context-dev.xml to have it use your personal site service
deploy-staging-personal:
  stage: deploy
  extends: .deploy_template    
  script: |
    export VERSION="current"
    export APP_SERVER="GNS Web Application Staging"
    appName="${APP_NAME}-${GITLAB_USER_LOGIN}"
    varName="port_prefix_${GITLAB_USER_LOGIN}"
    port="${!varName}040"  
    volSuffix="-${GITLAB_USER_LOGIN}"    
    ./deploy.sh "$appName" "$port" "$volSuffix" "staging" "gns-libs-snapshot"

deploy-prod:
  stage: deploy-prod
  only:
    - master    
  extends: .deploy_template       
  script: |
    export VERSION="0.0.38"
    export APP_SERVER="GNS Web Applications Internal"
    export APP_HOST="webapp-internal.gns.cri.nz"

    port=$(./cicdutils/available_tomcat_port.sh $APP_HOST $APP_PORTS)
    appName="$APP_NAME-$port"  
    volSuffix=""
    ./deploy.sh "$appName" "$port" "$volSuffix" "prod" "gns-libs-release"
