stages:
  - build
  - deploy
  - image

build:
  image: maven:3.8-openjdk-11
  tags:
    - docker
  stage: build
  except:
    - main
  script: |
    cp $settings_xml ~/.m2/settings.xml
    mvn clean deploy -ntp

  # artifacts:
  #   reports:
  #     junit:
  #       - target/surefire-reports/TEST-*.xml
  #     cobertura:
  #       - target/site/jacoco/jacoco.xml


release:
  image: openjdk:11
  tags:
    - docker
  stage: deploy
  only:
    - main
  script: |
    ./mvnw jgitflow:release-start -ntp -B -s .mvn/settings.xml
    ./mvnw jgitflow:release-finish -ntp -s .mvn/settings.xml

deploy:
  tags:
    - linux
  stage: deploy
  script: |
    NAME="$( echo -e 'setns x=http://maven.apache.org/POM/4.0.0\ncat /x:project/x:artifactId/text()' | xmllint --shell pom.xml | grep -v "^/")"
    VERSION="$( echo -e 'setns x=http://maven.apache.org/POM/4.0.0\ncat /x:project/x:version/text()' | xmllint --shell pom.xml | grep -v "^/")"
    IMAGE="$(echo -e 'setns x=http://maven.apache.org/POM/4.0.0\ncat /x:project/x:properties/x:image.name/text()' | xmllint --shell pom.xml | grep -v "^/" \
    | sed 's/${project.artifactId}/'"$NAME"'/' \
    | sed 's/${project.version}/'"$VERSION"'/')"
    APP_NAME="$(echo -e 'setns x=http://maven.apache.org/POM/4.0.0\ncat /x:project/x:properties/x:application.name/text()' | xmllint --shell pom.xml | grep -v "^/")"
    APP_SERVER="Applications Development"
    TEAM="GGW"
    DOCKER_CONFIG=(HostConfig:='{ "PortBindings": { "8080/tcp": [{ "HostPort": "9010" }] }, "RestartPolicy": {"Name":"always" } }' )
    ./docker_build.sh -i "$IMAGE"
    ./docker_deploy.sh -i "$IMAGE" -a "$APP_NAME" -s "$APP_SERVER" -t "$TEAM" -d "$DOCKER_CONFIG"

