spring.application.name=Site Revamp Dev
spring.main.banner-mode=off
management.endpoints.web.exposure.include=*

#there seems to be a library that is over riding this...
logging.config=classpath:logback-spring.xml