## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.datasource.url=jdbc:postgresql://hutd03.gns.cri.nz:5432/gns_dev
spring.datasource.username= application_w
spring.datasource.password= cH2KThMp
hibernate.dialect = org.hibernate.spatial.dialect.postgis.PostgisDialect
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.jpa.generate-ddl=false
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

logging.level.root=INFO

